### ISSUE TITLE
Error when running with parser=future on CentOS 7

### ISSUE THREAD

**Issue by crabmanX** [saz/puppet-ntp#24]
Error: Could not retrieve catalog from remote server: Error 400 on SERVER: Evaluation Error: Comparison of: Undef Value >= String, is not possible. Caused by 'Only Strings and Numbers are comparable'. at /etc/puppet/environments/testing/modules/ntp/manifests/params.pp:28:30 on node wiki.ekt.maschinenbau.tu-darmstadt.de

tested with version ff5b2d0

**Comment by saz** [comment]
This should be fixed with the merge of #25
