### ISSUE TITLE
Error while evaluating a Function Call, 'versioncmp' 

### ISSUE THREAD

**Issue by mphoraf** [saz/puppet-ntp#27]
When i ran `puppet agent --test` on `puppet 4.10.1` running `Centos 7.3.16111` the below problem happens.
===logs==
puppet agent --test
Info: Using configured environment 'production'
Info: Retrieving pluginfacts
Info: Retrieving plugin
Error: Could not retrieve catalog from remote server: Error 500 on SERVER: Server Error: Evaluation Error: Error while evaluating a Resource Statement, Evaluation Error: Error while evaluating a Function Call, 'versioncmp' parameter 'b' expects a String value, got Integer at /etc/puppetlabs/code/environments/production/modules/ntp/manifests/params.pp:28:14 on node foreman.raffbrains.com
Warning: Not using cache on failed catalog
Error: Could not retrieve catalog; skipping run
====logs===

i had to modify a line `if versioncmp($majdistrelease, 6) >= 0 {`
to be ```if versioncmp($majdistrelease, '6') >= 0 {```

Then it worked afterwards.

**Comment by jbro** [comment]
I can verify this, and have created a pull request with @mphoraf's suggestion.

**Comment by saz** [comment]
Fixed with the merge of #28
